### ISSUE TITLE
Question regarding Source.Receive, returning number of frames. Should it be number of samples?

### ISSUE THREAD

**Issue by mewmew** [zikichombo/sound#2]
From the documentation of [sound.Source](https://godoc.org/zikichombo.org/sound#Source), the `Receive` method places *samples* in d and returns number of *frames* placed in d.

Should the documentation refer to samples in both cases? I would guess that `sound.Source.Receive` would return the number of samples read (which may be more than the number of frames, since each frame may contain multiple samples).

**Comment by wsc1** [comment]
Thanks for the comments.

The sound.Seeker was definitely a documentation error, both should refer to frames.

The sound.Source.Receive method on the other hand doesn't sound confusing to me because it "places" samples in d, and d is a slice whose every element is a sample.

That said, can you suggest a rewording you would find more clear?

**Comment by mewmew** [comment]
> The sound.Source.Receive method on the other hand doesn't sound confusing to me because it "places" samples in d, and d is a slice whose every element is a sample.

My confusion was not related to the use of "places", I find it very clear and a good use of the verb. However, my confusion was the use of samples and frames.

From [sound.Source.Receive](https://godoc.org/zikichombo.org/sound#Source):

```go
// Receive places samples in d.
//
// Receive returns the number of frames placed in d together with
// any error.  Receive may use all of d as scatch space.
```

Lets say I have an audio file with 2 channels and 100 samples in length per channel. Now, imagine I have the following code:

```go
// source is the audio file mentioned above, with 2 channels and 100 samples in length per channel.
d := make([]float64, 50)
i, err := source.Receive(d)
if err != nil {
   log.Fatal(err)
}
// What is the value of i at this point?
```

* If the value of `i` is 25, then does *frames* refer to number of samples received per channel?
* If the value of `i` is 50, then does *frames* refer to number of samples received in total?

The use of frames seems confusing to me, as my frame of reference (no pun intended) to the term *frame* is based on the [FLAC specification](https://xiph.org/flac/format.html).

>  * **Frame**: A frame header plus one or more subframes. 
> * ** Subframe**: A subframe header plus one or more encoded samples from a given channel. All subframes within a frame will contain the same number of samples.

Also, part of the confusion may be based on the use of return in the following sentence.

```diff
-Receive may return 0 < n < len(d) samples only if the subsequent call will return (0, io.EOF).
+Receive may place 0 < n < len(d) samples in d only if the subsequent call will return (0, io.EOF).
```

**Comment by mewmew** [comment]
Basically what I'm asking is, what is the difference between a sample and a frame?

**Comment by wsc1** [comment]
Yes, there needs to be an intro terminology guide as it is not clear at all to newcomers and even in the audio tech terminology there are ambiguities.

In the repos, I have chosen "frame" to mean one sample for every channel, all sampled at the same point in time.  So 100 stereo samples is always 50 frames, 100 mono channel samples is always 100 frames.  

My understanding this that this usage is the standard one non-compressed/non-streaming contexts.  Codecs often define frames in the sense of chunking their data, which is a different meaning altogether.

Nonetheless, there was still a remaining documentation error in Receive w.r.t. len(d), which is fixed now.
Thanks for pointing it out.
